version: '3.8'

services:
  fox-blog:
    container_name: fox-blog
    build:
      context: ./fox-blog
      dockerfile: Dockerfile
    depends_on:
      - database
      - fox-blog-api
    volumes:
      - './fox-blog:/var/www'
      - '/var/www/node_modules'
    ports:
      - '3000:3000'
    networks:
      - app-network

  fox-blog-api:
    container_name: fox-blog-api
    build:
      context: ./fox-blog-api
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - './fox-blog-api:/var/www'
      - '/var/www/node_modules'
    ports:
      - '8000:3000'
    networks:
      - app-network
      
  database:
    container_name: "database"
    hostname: database
    image: postgres:12.3-alpine
    restart: always
    user: root
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: fox-blog_control
      POSTGRES_PASSWORD: root
    volumes:
      - ./database/tmp/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
  esdata:
    driver: local
  dbdata:
    driver: local
